### ISSUE TITLE
No Version Tagged

### ISSUE THREAD

**Issue by antbates1991** [ekomi-ltd/eKomi-integration-magento-2#1]
It would be nice to have a version of this module tagged. eg `1.1.0` so in the `composer.json` file you can reference it as `"ekomi/ekomiintegration": "1.1.0"` instead of "`ekomi/ekomiintegration": "dev-master#c6eaac1f709a5287d5bf031c162d3f6a8e1a3ada"`

**Comment by carlosgoncalves84** [comment]
I'm getting your github nitifications. I'm not working for ekomi. Pls
remove me from you mailing list.

2017-07-03 9:45 GMT+02:00 Anthony Bates <notifications@github.com>:

**Comment by SyedAbdullahShah** [comment]
@antbates1991 We're now adding tags for each release, you can reference it as 

> "ekomi/ekomiintegration": "v1.2.1"

 in the 

> composer.json
