### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by kevlj** [ekomi-ltd/eKomi-integration-magento-2#12]
Hi, we have installed the extension on our clients site and we get the following error during the compilation process.

`Errors during compilation:
	Ekomi\EkomiIntegration\Block\Widget\Reviews
		Incorrect dependency in class Ekomi\EkomiIntegration\Block\Widget\Reviews in /var/www/html/vendor/ekomiltd/ekomiintegration/Block/Widget/Reviews.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 1`

The error is caused by `use Magento\Store\Model\StoreManagerInterface;` in the file which has already been included and triggering the error when being called again.

**Comment by SyedAbdullahShah** [comment]
@kevlj Hi
We have removed incorrect dependencies for Magento 2.3, please update the plugin to 2.0.1 and it should work fine.
Thanks.
