### ISSUE TITLE
Magento 2.3: errors in compile process

### ISSUE THREAD

**Issue by joinso** [ekomi-ltd/eKomi-integration-magento-2#13]
Hi!

After upgrade to Magento 2.3, we get this error when we try to compile:

PHP Fatal error:  Cannot use Magento\Framework\DataObject as Object because 'Object' is a special class name in /<MAGENTO_FOLDER>/app/code/Ekomi/EkomiIntegration/Observer/SendOrderToEkomi.php on line 14

Any idea?

Regards,
JOINSO

**Comment by SyedAbdullahShah** [comment]
Hi
We have removed incorrect dependencies for Magento 2.3, please update the plugin to 2.0.1 and it should work fine.
Thanks.

**Comment by joinso** [comment]
Ok, now it works as expected.
No errors found.

Regards,
JOINSO
