### ISSUE TITLE
Support for Magento 2.2

### ISSUE THREAD

**Issue by nicobatty** [ekomi-ltd/eKomi-integration-magento-2#2]
Do this module support Magento 2.2?

I can see that the max PHP version is 7.0.x.

https://github.com/ekomi-ltd/eKomi-integration-magento-2/blob/c6eaac1f709a5287d5bf031c162d3f6a8e1a3ada/composer.json#L11

so it doesn't officially work on the max available PHP option for Magento 2.2 (http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html#php).

**Comment by SyedAbdullahShah** [comment]
Yes, the module does support Magento 2.
We have updated the composer.json in the latest update.
