### ISSUE TITLE
composer install issue

### ISSUE THREAD

**Issue by danj-O** [ekomi-ltd/eKomi-integration-magento-2#36]
The extension shows up in my dashboard after following the composer steps.  When I try to get it to display on my homepage, nothing happens.  Any help would be greatly appreciated.  My goal is to display the company reviews, not product reviews.

**Comment by nauman-coeus** [comment]
Hi,
Hope you are doing well. The widget implementation was in the older version of the plugin however even in that version the plugin only supported Product widget. Still if you want seller widget on home page you can ask our support on the link below 

https://support.ekomiapps.de/en/
