### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Pankaj8460** [ekomi-ltd/eKomi-integration-magento-2#41]
Hello Team,

can you please check below screenshots and suggest actually what's problem here. Thank you!

https://prnt.sc/zhpvjr
https://prnt.sc/zhpyzd

**Comment by zaheerabbass** [comment]
Hi @Pankaj8460 
Can you please tell steps to reproduce the issue? @shahzad-ahmad will help us to resolve it. 

Thanks.
