### ISSUE TITLE
Configuration path changed, but no db-upgrade script

### ISSUE THREAD

**Issue by netzkollektiv** [ekomi-ltd/eKomi-integration-magento-2#53]
As mentioned in #50 the configuration path was changed, but there is no upgrade script provided. This led to Ekomi being disabled after the update.

**Comment by faisaliftikhar66** [comment]
@netzkollektiv That particular issue already fixed in release 2.5.8, please update the plugin by downloading it from https://ekomi01.atlassian.net/wiki/spaces/KB/pages/1193148517/eKomi+Official+Magento+2+Plugin
Do let us know if you still face issue.
Regards
Faisal

**Comment by netzkollektiv** [comment]
Thanks for the quick answer! We use composer to install and update the plugin. If you do not keep composer up to date it would be good to remove the package from there :-)

**Comment by faisaliftikhar66** [comment]
@netzkollektiv You welcome, no need to remove from package, if you are using the composer to update then you can give tag/release version, here is the details of new release :) 
https://github.com/ekomi-ltd/eKomi-integration-magento-2/releases/tag/2.5.8

**Comment by netzkollektiv** [comment]
@faisaliftikhar66 but v2.5.8 is the version we have installed via composer - and the update script seems to be missing.

**Comment by faisaliftikhar66** [comment]
@netzkollektiv Please see the change at here : https://github.com/ekomi-ltd/eKomi-integration-magento-2/commit/e9ab62769509620b299e5459358ef1c966714d05
That particular commit exist in that tag release 2.5.8
I think you need to update your composer :) 
Regards
Faisal

**Comment by netzkollektiv** [comment]
@faisaliftikhar66 I do see the change, thank you. 

Unfortunately it does not help migrating the old config to the new path. You need to adapt the config of earlier versions using a data upgrade script when running `setup:upgrade` Otherwise merchants are loosing there settings when upgrading.

https://devdocs.magento.com/guides/v2.4/extension-dev-guide/declarative-schema/data-patches.html
